server:
  port: 8033

spring:
  datasource:                                           # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动
    url: jdbc:mysql://192.168.228.129:3306/app?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456

  redis:
    database: 0
    host: 192.168.228.129
    port: 6379

fdfs:
  connect-timeout: 30
  so-timeout: 30
  tracker-list: 192.168.228.129:22122
